Belajar Numpy

In [76]:
import numpy as np
np.__version__

'1.21.5'

## Python List

In [22]:
ipk_as_list = [4.0, 3.2, 3.5]

In [23]:
ipk_as_list.append(4.0) #append menambahkan diakhir
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

In [24]:
ipk_as_list.insert(1, "Belum ada")#menambahkan di tengah
ipk_as_list

[4.0, 'Belum ada', 3.2, 3.5, 4.0]

In [25]:
ipk_as_list.pop(1) #menghapus
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

## Numpy Array

In [81]:
ipk = np.array(ipk_as_list)

In [83]:
ipk.dtype

dtype('float64')

In [84]:
ipk.size

4

## Study Log

In [85]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [86]:
%whos

Variable        Type           Data/Info
----------------------------------------
fake_log        ndarray        100: 100 elems, type `uint16`, 200 bytes
index           ndarray        2x2: 4 elems, type `int32`, 16 bytes
ipk             ndarray        4: 4 elems, type `float64`, 32 bytes
ipk_as_list     list           n=4
np              module         <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
practice        ndarray        42: 42 elems, type `int32`, 168 bytes
pratice         ndarray        7x6: 42 elems, type `int32`, 168 bytes
rand            RandomState    RandomState(MT19937)
students_ipk    ndarray        3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray        100: 100 elems, type `uint16`, 200 bytes


## Array Multidimensi

In [87]:
students_ipk = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.7, 3.5, 3.5, 4.0],
    [3.0, 3.3, 3.5, 4.0]
], np.float16)
students_ipk

array([[4. , 3.3, 3.5, 4. ],
       [3.7, 3.5, 3.5, 4. ],
       [3. , 3.3, 3.5, 4. ]], dtype=float16)

In [88]:
students_ipk.ndim #buat cek array berapa dimensi

2

In [90]:
students_ipk.shape #buat cek berapa elemen

(3, 4)

In [91]:
students_ipk[2] #buat manggil

array([3. , 3.3, 3.5, 4. ], dtype=float16)

In [37]:
students_ipk[1][2]#akan tampil 3.5, urutan ke satu nomor dua

3.5

## STudy Log MultiDimensi

In [92]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [52]:
study_minutes[1][0]=60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [55]:
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [60]:
[fake_log[1], fake_log[21]] 

[45, 52]

In [63]:
fake_log[[1, 21]]

array([45, 52], dtype=uint16)

In [64]:
index = np.array([
    [1, 21],
    [1, 2]
])
fake_log[index] #buat merapikan

array([[45, 52],
       [45, 70]], dtype=uint16)

In [94]:
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [95]:
practice = np.arange(42)
practice.shape =(7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [96]:
practice[2, 1]

13

In [97]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [100]:
practice[2:5, 3]

array([15, 21, 27])

In [101]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])