Belajar Numpy

In [21]:
import numpy as np
np.__version__

'1.21.5'

## Python List

In [22]:
ipk_as_list = [4.0, 3.2, 3.5]

In [23]:
ipk_as_list.append(4.0) #append menambahkan diakhir
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

In [24]:
ipk_as_list.insert(1, "Belum ada")#menambahkan di tengah
ipk_as_list

[4.0, 'Belum ada', 3.2, 3.5, 4.0]

In [25]:
ipk_as_list.pop(1) #menghapus
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

## Numpy Array

In [26]:
ipk = np.array(ipk_as_list)

In [27]:
ipk.dtype

dtype('float64')

In [28]:
ipk.size

4

## Study Log

In [29]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [31]:
%whos

Variable        Type       Data/Info
------------------------------------
ipk             ndarray    4: 4 elems, type `float64`, 32 bytes
ipk_as_list     list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


## Array Multidimensi

In [32]:
students_ipk = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.7, 3.5, 3.5, 4.0],
    [3.0, 3.3, 3.5, 4.0]
], np.float16)
students_ipk

array([[4. , 3.3, 3.5, 4. ],
       [3.7, 3.5, 3.5, 4. ],
       [3. , 3.3, 3.5, 4. ]], dtype=float16)

In [33]:
students_ipk.ndim #buat cek array berapa dimensi

2

In [34]:
students_ipk.shape #buat cek berapa elemen

(3, 4)

In [36]:
students_ipk[2] #buat manggil

array([3. , 3.3, 3.5, 4. ], dtype=float16)

In [37]:
students_ipk[1][2]#akan tampil 3.5, urutan ke satu nomor dua

3.5