Belajar Numpy

In [19]:
import numpy as np
np.__version__

'1.21.5'

## Python List

In [20]:
ipk_as_list = [4.0, 3.2, 3.5]

In [21]:
ipk_as_list.append(4.0) #append menambahkan diakhir
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

In [22]:
ipk_as_list.insert(1, "Belum ada")#menambahkan di tengah
ipk_as_list

[4.0, 'Belum ada', 3.2, 3.5, 4.0]

In [23]:
ipk_as_list.pop(1) #menghapus
ipk_as_list

[4.0, 3.2, 3.5, 4.0]

## Numpy Array

In [24]:
ipk = np.array(ipk_as_list)

In [25]:
ipk.dtype

dtype('float64')

In [26]:
ipk.size

4

## Study Log

In [27]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [28]:
%whos

Variable             Type       Data/Info
-----------------------------------------
index                ndarray    2x2: 4 elems, type `int32`, 16 bytes
ipk                  ndarray    4: 4 elems, type `float64`, 32 bytes
ipk_as_list          list       n=4
not_copied           ndarray    7x6: 42 elems, type `int32`, 168 bytes
np                   module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
practice             ndarray    7x6: 42 elems, type `int32`, 168 bytes
practice_list        list       n=3
practice_list_copy   list       n=3
study_minutes        ndarray    100: 100 elems, type `uint16`, 200 bytes


## Array Multidimensi

In [29]:
students_ipk = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.7, 3.5, 3.5, 4.0],
    [3.0, 3.3, 3.5, 4.0]
], np.float16)
students_ipk

array([[4. , 3.3, 3.5, 4. ],
       [3.7, 3.5, 3.5, 4. ],
       [3. , 3.3, 3.5, 4. ]], dtype=float16)

In [30]:
students_ipk.ndim #buat cek array berapa dimensi

2

In [31]:
students_ipk.shape #buat cek berapa elemen

(3, 4)

In [32]:
students_ipk[2] #buat manggil

array([3. , 3.3, 3.5, 4. ], dtype=float16)

In [33]:
students_ipk[1][2]#akan tampil 3.5, urutan ke satu nomor dua

3.5

## STudy Log MultiDimensi

In [34]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [35]:
study_minutes[1][0]=60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [36]:
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [37]:
[fake_log[1], fake_log[21]] 

[45, 52]

In [38]:
fake_log[[1, 21]]

array([45, 52], dtype=uint16)

In [39]:
index = np.array([
    [1, 21],
    [1, 2]
])
fake_log[index] #buat merapikan

array([[45, 52],
       [45, 70]], dtype=uint16)

In [40]:
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [41]:
practice = np.arange(42)
practice.shape =(7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [42]:
practice[2, 1]

13

In [43]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
practice[2:5, 3]

array([15, 21, 27])

In [45]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

## Copy Vs View

In [46]:
practice_list = [1, 2, 3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [47]:
not_copied = practice[:]
not_copied [0, 0] = 12345
practice, not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [48]:
print(practice.base)

None


In [49]:
print(not_copied.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [50]:
not_copied.base is practice

True

In [52]:
not_copied.base is practice_list

False

## Filter Array dengan kondisi

## Mencari durai belajar dibawah 1 jam (60menit)

In [56]:
fake_log < 60
fake_log [fake_log < 60]

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

In [58]:
results = []
for value in fake_log:
    if value < 60:
        results.append(value)
    
np.array(results)

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

In [60]:
study_minutes = np.zeros(100, np.uint16)
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  99,  45,  70, 162,
       146,  70, 177, 176,  47, 148, 123,  67,  90, 122,  34, 160, 135,
       102,  62,  61,  85,  52, 153, 128,  89,  37, 109,  60, 128,  57,
       160,  67, 144,  97, 150, 148,  32, 155, 116, 137,  49,  70, 159,
       159,  84, 114,  93, 110,  81, 122, 103,  53,  52, 147,  75,  93,
        45,  46, 177,  91,  70,  69,  46, 150,  86, 170, 174, 143,  88,
        71, 132,  67, 157, 118,  91, 158, 178, 176,  37, 155,  4

In [63]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

## Aljabar Linear

In [66]:
orders = np.array ([
    [2, 0, 0, 0],
    [1, 0, 2, 4],
    [1, 2, 1, 0],
    [4, 6, 0, 2]
])
totals = np.array([20000, 32000, 20000, 61000])
prices = np.linalg.solve(orders, totals)
prices


array([10000.,  2500.,  5000.,  3000.])

In [69]:
orders @ prices

array([20000., 32000., 20000., 61000.])

## Fungsi Universal

In [72]:
a, b = np.split(np.arange(1, 11), 2)
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [74]:
a + b

array([ 7,  9, 11, 13, 15])

In [75]:
a * b

array([ 6, 14, 24, 36, 50])

In [81]:
a - b

array([-5, -5, -5, -5, -5])

In [82]:
b - a

array([5, 5, 5, 5, 5])

In [84]:
a

array([1, 2, 3, 4, 5])

In [85]:
a + 3

array([4, 5, 6, 7, 8])

In [86]:
a + np.repeat(3, 5)

array([4, 5, 6, 7, 8])

In [83]:
b

array([ 6,  7,  8,  9, 10])

In [89]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1, x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [90]:
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [91]:
np.add(x1, 2)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])